### ISSUE TITLE
When trying -o: "syntax error in expression"

### ISSUE THREAD

**Issue by mdPlusPlus** [PassthroughPOST/VFIO-Tools#1]
I'm trying to pass my Powercolor RX Vega 64 to my guest as shown in this screenshot:   
![Screenshot](https://i.imgur.com/hg71jHZ.png)   

When I use `sudo vfioselect -o` I get the following error:   
>/etc/modprobe.d/vfioselect.conf written successfully.
>Bind:   30:00.0
>30:00.1
>Unbind: 
>
>./vfioselect: line 107: 30:00.0
>30:00.1: syntax error in expression (error token is ":00.0
>30:00.1")

When I start it without the `-o` switch I have no problems however.

~~**EDIT**: After a reboot the devices are actually still bound to `amdgpu` instead of `vfio-pci`. So even when it's not giving me an error message, it is actually not working.~~

~~Guess I'll go back to manually edit the module files myself.~~

**EDIT 2**: Sry, it actually works after issuing a `sudo update-initramfs -u`. There should be a notification that this update is not automatically performed by `vfioselect`.   
There's still the syntax error when using the `-o` switch, though.

**Comment by ShoelaceMan** [comment]
Hello,

I'm not opposed to fixing this, but I do have a question about your configuration first. Based on this report, you're trying to set up a VM with GPU passthrough, but may I ask why you're wanting to bind your card with vfio-pci since this is handled automatically now? For example, your XML should look as follows:
```
<hostdev mode='subsystem' type='pci' managed='yes'>
  <source>
    <address domain='0x0000' bus='0xb3' slot='0x00' function='0x1'/>
  </source>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x0e' function='0x0'/>
</hostdev>
```

As you can see in the `hostdev` section is the value `managed='yes'`, which virt-manager enables by default. When this value is set, libvirt will try to bind the card with vfio-pci automatically before attempting to boot. In my most recent VFIO set up, passing my GPU was a one click operation that didn't require modprobe rules, or initrd modification. Please try this, and get back with me on your results, as I haven't had enough test cases of this feature to justify deprecating online binding altogether. 

As for your other suggestion about initrd, I can make a general warning that indicates vfioselect not modifying your initrd, but I feel this is beyond the scope of the project, as in some situations it is completely unnecessary to begin with, but several environments would require different configurations as well (fedora/centos/RHEL > dracut, Arch/slackware > mkinitcpio, ubuntu/debian/mint > update-initramfs). That being the case, how would you suggest bringing this to the user's attention?

**Comment by mdPlusPlus** [comment]
Well, the managed mode doesn't work for me. When I'm not binding my graphics card to vfio-pci beforehand, all that happens is that my host freezes. (Kernel 4.16.2, amdgpu driver, RX550 host, RX Vega 64 guest)

Regarding the notification a simple "Update your initramfs for the changes to take effect." would be sufficient.

**Edit**: Accidently switched guest and host. Corrected.

**Comment by ShoelaceMan** [comment]
I'll add the message, but aren't you trying to pass your Vega? Manage mode in libvirt cannot kill your Xorg instance and start the VM, you need to have the guess card rendering/calculating nothing at the time of boot up. Can you double check your XML and let me know?

**Comment by mdPlusPlus** [comment]
<hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x30' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </hostdev>
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x30' slot='0x00' function='0x1'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </hostdev>

I don't see anything wrong with the xml file.

How can I make sure my guest card isn't rendering anything at the time of the bootup?  
Is there a specific Xorg config (I'm not using Wayland, btw) to achieve this?   
Would it be sufficient to change the Xorg config and restart Xorg before starting the VM?

**Comment by mdPlusPlus** [comment]
So I figured out what the syntax error was about:

When iteratiing through the arrays (`${bindids[@]}` and `${unbindids[@]}`) in `bind()` and `unbind()` you don't get single entries in `id` when issuing for `id in ${NAME}`, instead you get the whole array.
(As in not getting two ids "30:00.0" and "30:00.1" but instead getting one id containing two lines:   
"30:00.0   
30:00.1")

You have to change the iteration call to the following to get access to single IDs in `ìd`:

    while read -r id; do
        [stuff with $id]
    done <<< "${bindids[@]}"

After changing that I don't get the syntax error anymore and the card actually gets passed to vfio-pci.
 
Unfortunately my system crashes after that (probably because of X rendering on the card like you mentioned earlier), so I can't delve into it any deeper. (At least not without knowing how to properly configure X).

**Comment by ShoelaceMan** [comment]
Hey,

Sorry for the wait, as I mentioned in the pull request, I haven't had much motivation to work on this since seeing the manage hook in libvirt. Instead of redirecting as you've shown here, I've decided to fix the code that I didn't write correctly in an earlier function. After testing on my machine, the script should be fully functional now. Let me know if you have any more issues.
