### ISSUE TITLE
Somewhat confused about the hugepages hooks

### ISSUE THREAD

**Issue by JaneSmith** [PassthroughPOST/VFIO-Tools#7]
I'm no expert, so please forgive me if I'm missing something obvious here. But when I look at the two hooks for hugepages - `alloc_hugepages.sh` and `unalloc_hugepages.sh` - two things appear odd to me:

1. The comment block at the top instructs the user to place both files into both `/prepare/begin/` and `/release/end/`. Is this really correct? Surely you would only want the alloc hook when starting up the VM, and would only want the unalloc hook when shutting it down?

2. The alloc hook defines a `prepMemory` function, but as far as I can tell (with my limited Bash knowledge), nothing ever calls it? Is it not important to prepare that memory for allocation?

**Comment by SharkWipf** [comment]
You seem to be absolutely right on both your points, looks like this script still has some artifacts from before it was used as a hook script. I'm a bit too busy to fix it right now, but once I get around to it I'll see if I can clean it up.

The stuff called in `prepMemory` function I believe is used to reduce memory fragmentation if possible, it can be optimized further by dropping caches and running `sync` beforehand, which I thought this script was already doing, but apparently it's doing nothing of the sort. 
Whether it's important or not depends on your situation, if your memory's too fragmented you cannot dynamically allocate "static" hugepages this way, and the memory preparation should help get it less fragmented, but it may work fine without if your memory isn't fragmented to begin with.
I'll see if I can get around to cleaning it up soon, thanks for bringing it to my attention.

FWIW, the actual utility of this hugepages script is relatively little without further configuration nowadays, as Qemu will automatically set up transparent hugepages for VMs in its default configuration. Unless you configure a different default size for your static hugepages (i.e. 1G instead of 2M), "dynamic" static hugepages by way of this script perform exactly the same as the default transparent hugepages, while being more of a hassle to set up.

**Comment by SharkWipf** [comment]
I believe this got fixed months ago already but never reported back, so I think this can be closed.
