### ISSUE TITLE
How generate TOTAL_CORES_MASK and HOST_CORES_MASK

### ISSUE THREAD

**Issue by sl1pkn07** [PassthroughPOST/VFIO-Tools#8]
https://github.com/PassthroughPOST/VFIO-Tools/blob/b6b069bc18746e3d46c425cf0a05b4e80bbf2f24/libvirt_hooks/hooks/cset.sh#L22

https://github.com/PassthroughPOST/VFIO-Tools/blob/b6b069bc18746e3d46c425cf0a05b4e80bbf2f24/libvirt_hooks/hooks/cset.sh#L24

how to generate this values?

i have a 48thread machine (dual cpu), i have pinning my VM like this

~~~xml
  <cputune>
    <vcpupin vcpu='0' cpuset='10'/>
    <vcpupin vcpu='1' cpuset='34'/>
    <vcpupin vcpu='2' cpuset='11'/>
    <vcpupin vcpu='3' cpuset='35'/>
    <vcpupin vcpu='4' cpuset='22'/>
    <vcpupin vcpu='5' cpuset='46'/>
    <vcpupin vcpu='6' cpuset='23'/>
    <vcpupin vcpu='7' cpuset='47'/>
  </cputune>
~~~

and use this in kernel parameters

~~~
isolcpus=10,11,22,23,34,35,46,47 nohz_full=10,11,22,23,34,35,46,47 rcu_nocbs=10,11,22,23,34,35,46,47
~~~

how adapt these values to my config?

greetings

**Comment by SharkWipf** [comment]
Somehow I completely missed this issue, my apologies.
While I doubt you still need it, I'll admit I have no idea how mask calculation works or where the script even came from (it was contributed by another VFIO user who'd already got it from somewhere else I believe).
These scripts were only meant to be included as examples, and since I didn't write them, support for them is kind of out of scope.  

There are mask calculators that should do the trick however, for example this one: https://bitsum.com/tools/cpu-affinity-calculator/
